apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

commonLabels:
  app: gitops-sample-app

images:
- name: gitops-app-sample
  newName: pulllogictejacontainerregistry.azurecr.io/gitops-app-sample
  newTag: 9ccd9d12452ba6e85bc12b93a3c216409c9cecfc
- name: gitops-sample-app
  newName: docker.io/ramakrishnateja/gitops-sample-app
  newTag: 5d44f786813d0b33bb50c8f873060d0004c7bb1e

patchesJson6902:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
