apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

commonLabels:
  app: gitops-sample-app

commonAnnotations:
  azure-pipelines/planUrl: '#{PlanUrl}#'
  azure-pipelines/projectId: '#{ProjectId}#'
  azure-pipelines/hubName: '#{HubName}#'
  azure-pipelines/planId: '#{PlanId}#'
  azure-pipelines/jobId: '#{JobId}#'
  azure-pipelines/timelineId: '#{TimelineId}#'
  azure-pipelines/taskInstanceId: '#{TaskInstanceId}#'

images:
- name: gitops-app-sample
  newName: pulllogictejacontainerregistry.azurecr.io/gitops-app-sample
  newTag: 3829ef2ec3249a37fa82dd1dcccacfa1b3e5197f

patchesJson6902:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
