apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

commonLabels:
  app: gitops-sample-app

commonAnnotations:
  azure-pipelines/hubName: build
  azure-pipelines/jobId: b13a961e-e955-518a-e7c0-f390d7a9eeea
  azure-pipelines/planId: 799006ec-eb3f-4619-a856-7a85923bd685
  azure-pipelines/planUrl: https://chilakaluripet.visualstudio.com/
  azure-pipelines/projectId: 6646ead6-5b85-4380-b293-95af81a11aa0
  azure-pipelines/taskInstanceId: 5de78bf4-e6e7-588d-3810-1b4306da139a
  azure-pipelines/timelineId: 799006ec-eb3f-4619-a856-7a85923bd685

images:
- name: gitops-app-sample
  newName: pulllogictejacontainerregistry.azurecr.io/gitops-sample-app
  newTag: 874c513b1951fd370d3436ab2b156f15db6c10c6

patchesJson6902:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
