apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - service.yaml

images:
  - name: app
    newName: docker.io/ramakrishnateja/gitops-sample-app
    newTag: v1